### ISSUE TITLE
Move to Browserslist org

### ISSUE THREAD

**Issue by ai** [browserslist/vim-browserslist#1]
Let’s promote the plugin a little.

- [x] Move your plugin to `browserslist` org (I sent you an invite to org)
- [x] Send PR to `browserslist/browserslist` with “Syntax Highlight” section creation, moving VS Code plugin to that section and adding Vim plugin

**Comment by antonk52** [comment]
The plugin is now under the browserslist org and the PR for the docs can be seen [here](https://github.com/browserslist/browserslist/pull/568)
